language: python
python:
  - 3.7
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

install:
  - pip install -r binder/requirements.txt
  - pip install -r docs/requirements.txt

script:
  - make -C docs html
