name: Execute notebooks top to bottom to ensure no errors.
on:
  push:
  pull_request:
  schedule:
      - cron: '00 4 * * *'  # daily at 4AM 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout files in repo.
      uses: actions/checkout@main

    - name: Set up Python 3.x.
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install jupyter-repo2docker
      shell: bash -l {0}
      run: |
        set -vxeuo pipefail
        python -m pip install -r binder/requirements-dev.txt

    - name: Execute notebooks with Jupyter Book.
      shell: bash -l {0}
      run: |
        set -vxeuo pipefail
        jupyter-repo2docker . /bin/bash -c "jupyter-book build ."
